config/routes.rb
# encoding: UTF-8

# Copyright 2011-2013 innoQ Deutschland GmbH
#
# Licensed under the Apache License, Version 2.0 (the 'License');
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an 'AS IS' BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

Rails.application.routes.draw do
  # no more redirection, no more scope (handled by phusion passenger now)
  # get '/', to: redirect('/vocabulary')
  # scope '/vocabulary' do
  apipie

  scope ':lang', constraints: Iqvoc.routing_constraint do
    Iqvoc.localized_routes.each do |hook|
      hook.call(self)
      ActiveSupport::Deprecation.warn <<-EOF
        Adding routes via `Iqvoc.localized_routes` is deprecated and will
        be removed in iQvoc 4.5.
      EOF
    end

    resource  :user_session, only: [:new, :create, :destroy]
    resources :users, except: [:show]
    resources :concepts do
      member do
        get 'glance'
      end
    end
    resources :collections
    resources :imports, only: [:index, :show, :create]
    resources :exports, only: [:index, :show, :create] do
      get 'download'
    end

    get 'scheme' => 'concepts/scheme#show', as: 'scheme'
    get 'scheme/edit' => 'concepts/scheme#edit', as: 'edit_scheme'
    patch 'scheme' => 'concepts/scheme#update'

    get 'hierarchy' => 'hierarchy#index'
    get 'hierarchy/:root' => 'hierarchy#show'

    get 'triplestore_sync' => 'triplestore_sync#index'
    post 'triplestore_sync' => 'triplestore_sync#sync'

    post 'concepts/:origin/branch'      => 'concepts/versions#branch',    as: 'concept_versions_branch'
    post 'concepts/:origin/merge'       => 'concepts/versions#merge',     as: 'concept_versions_merge'
    post 'concepts/:origin/lock'        => 'concepts/versions#lock',      as: 'concept_versions_lock'
    post 'concepts/:origin/unlock'      => 'concepts/versions#unlock',    as: 'concept_versions_unlock'
    post 'concepts/:origin/to_review'   => 'concepts/versions#to_review', as: 'concept_versions_to_review'
    get 'concepts/:origin/consistency_check' => 'concepts/versions#consistency_check', as: 'concept_versions_consistency_check'

    patch 'concepts/:origin/move'        => 'concepts_movement#move',     as: 'move_concept'

    post 'collections/:origin/branch'      => 'collections/versions#branch',    as: 'collection_versions_branch'
    post 'collections/:origin/merge'       => 'collections/versions#merge',     as: 'collection_versions_merge'
    post 'collections/:origin/lock'        => 'collections/versions#lock',      as: 'collection_versions_lock'
    post 'collections/:origin/unlock'      => 'collections/versions#unlock',    as: 'collection_versions_unlock'
    post 'collections/:origin/to_review'   => 'collections/versions#to_review', as: 'collection_versions_to_review'
    get 'collections/:origin/consistency_check' => 'collections/versions#consistency_check', as: 'collection_versions_consistency_check'

    get 'alphabetical_concepts(/:prefix)' => 'concepts/alphabetical#index', as: 'alphabetical_concepts'
    get 'untranslated_concepts/:prefix'   => 'concepts/untranslated#index', as: 'untranslated_concepts'
    get 'hierarchical_concepts' => 'concepts/hierarchical#index', as: 'hierarchical_concepts'
    get 'expired_concepts' => 'concepts/expired#index', as: 'expired_concepts'

    get 'dashboard' => 'dashboard#concept_index', as: 'dashboard'
    get 'dashboard_glance' => 'dashboard#glance', as: 'dashboard_glance'
    get 'collection_dashboard' => 'dashboard#collection_index', as: 'collection_dashboard'
    match 'dashboard/reset' => 'dashboard#reset', as: 'reset', via: [:get, :post]

    get 'config' => 'instance_configuration#index', as: 'instance_configuration'
    patch 'config' => 'instance_configuration#update'

    get 'search' => 'search_results#index', as: 'search'

    get 'help' => 'pages#help', as: 'help'
    get 'version' => 'pages#version', as: 'version'
    get 'components' => 'pages#components', as: 'components'

    get '/' => 'frontpage#index', as: 'localized_root'
  end

  patch ':origin/add_match' => 'reverse_matches#add_match', as: 'add_match'
  patch ':origin/remove_match' => 'reverse_matches#remove_match', as: 'remove_match'

  get 'remote_labels' => 'remote_labels#show', as: 'remote_label'
  get 'schema' => redirect('/'), as: 'schema'
  get 'dataset' => 'rdf#dataset', as: 'rdf_dataset'
  get 'scheme' => 'concepts/scheme#show', as: 'rdf_scheme'
  get 'search' => 'search_results#index', as: 'rdf_search'
  get 'hierarchy' => 'hierarchy#index'
  get 'hierarchy/:root' => 'hierarchy#show'

  get ':id' => 'rdf#show', as: 'rdf'
  
  root to: 'frontpage#index', format: nil
# was: /vocabulary scope
# end
end

app/models/concept/relation/skos/broader/base.rb
# encoding: UTF-8

# Copyright 2011-2013 innoQ Deutschland GmbH
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

class Concept::Relation::SKOS::Broader::Base < Concept::Relation::SKOS::Base
  self.rdf_predicate = 'broader'

  def self.narrower_class
    Concept::Relation::SKOS::Narrower::Base
  end

  def self.reverse_relation_class
    self.narrower_class
  end

  def self.view_section(obj)
    'main'
  end

  def self.view_section_sort_key(obj)
    100
  end

  def self.narrower_editable
    !singular?
  end
end

app/controllers/concepts/alphabetical_controller.rb
# encoding: UTF-8

# Copyright 2011-2013 innoQ Deutschland GmbH
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

require 'concerns/dataset_initialization'

class Concepts::AlphabeticalController < ConceptsController
  include DatasetInitialization

  def index
    authorize! :read, Concept::Base

    # only initilaize dataset if dataset param is set
    # prevent obsolet http request when using matches widget
    datasets = params[:dataset] ? init_datasets : []

    identify_used_first_letters

    if dataset = datasets.detect { |dataset| dataset.name == params[:dataset] }
      query = params[:prefix].mb_chars.downcase.to_s
      @search_results = dataset.alphabetical_search(query, I18n.locale) || []
      @search_results = Kaminari.paginate_array(@search_results).page(params[:page])
    else
      @search_results = find_labelings

      # When in single query mode, AR handles ALL includes to be loaded by that
      # one query. We don't want that! So let's do it manually :-)
      includes = Iqvoc::Concept.base_class.default_includes
      if Iqvoc::Concept.note_classes.include?(Note::SKOS::Definition)
        includes << Note::SKOS::Definition.name.to_relation_name
      end
      ActiveRecord::Associations::Preloader.new.preload(@search_results, owner: includes)

      @search_results.to_a.map! { |pl| AlphabeticalSearchResult.new(pl) }
    end

    respond_to do |format|
      format.html { render :index, layout: with_layout? }
    end
  end

  protected

  def identify_used_first_letters
    @letters = Label::Base.where("#{Label::Base.table_name}.language = ?", I18n.locale).joins(:pref_labeled_concepts).where("concepts.published_at IS NOT NULL").where("concepts.expired_at IS NULL OR concepts.expired_at >= ?", Time.now).where("concepts.type = ?", Iqvoc::Concept.base_class_name).select("DISTINCT UPPER(SUBSTR(value, 1, 1)) AS letter").order("letter").map(&:letter)
  end

  def find_labelings
    query = (params[:prefix] || @letters.first || 'a').mb_chars.downcase.to_s

    Iqvoc::Concept.pref_labeling_class.
      concept_published.
      concept_not_expired.
      label_begins_with(query).
      by_label_language(I18n.locale).
      includes(:target).
      order("LOWER(#{Label::Base.table_name}.value)").
      joins(:owner).
      where(concepts: { type: Iqvoc::Concept.base_class_name }).
      references(:concepts, :labels, :labelings).
      page(params[:page])
  end
end

app/controllers/concepts/expired_controller.rb
# encoding: UTF-8

# Copyright 2011-2013 innoQ Deutschland GmbH
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

class Concepts::ExpiredController < Concepts::AlphabeticalController
  protected

  def identify_used_first_letters
    @letters = Label::Base.where("#{Label::Base.table_name}.language = ?", I18n.locale).joins(:pref_labeled_concepts).where("concepts.expired_at < ?", Time.now).where("concepts.type = ?", Iqvoc::Concept.base_class_name).select("DISTINCT UPPER(SUBSTR(value, 1, 1)) AS letter").order("letter").map(&:letter)
  end

  def find_labelings
    query = (params[:prefix] || @letters.first || 'a').mb_chars.downcase.to_s

    Iqvoc::Concept.pref_labeling_class.
      concept_expired.
      label_begins_with(query).
      by_label_language(I18n.locale).
      includes(:target).
      order("LOWER(#{Label::Base.table_name}.value)").
      joins(:owner).
      where(concepts: { type: Iqvoc::Concept.base_class_name }).
      references(:concepts, :labels, :labelings).
      page(params[:page])
  end
end

app/controllers/concepts/scheme_controller.rb
# encoding: UTF-8

# Copyright 2011-2013 innoQ Deutschland GmbH
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

class Concepts::SchemeController < ApplicationController
  resource_description do
    name 'Concept scheme'
  end

  api :GET, 'scheme', "The concept scheme lists the vocabulary's top concepts."
  formats [:html, :ttl, :rdf]
  example <<-DOC
    GET /scheme.ttl
    200

    # omitted namespace definitions
    :achievement_hobbies a skos:Concept;
                         skos:topConceptOf :scheme;
                         skos:inScheme :scheme;
                         skos:prefLabel "Achievement hobbies"@en;
                         skos:narrower :gardening.
    :scheme a skos:ConceptScheme;
            skos:hasTopConcept :achievement_hobbies.
  DOC

  def show
    @scheme = Iqvoc::Concept.root_class.instance
    authorize! :read, @scheme

    @top_concepts = Iqvoc::Concept.base_class.tops.published.sort_by {|c| c.pref_label }

    respond_to do |format|
      format.html
      format.any(:rdf, :ttl, :nt)
    end
  end

  def edit
    @scheme = Iqvoc::Concept.root_class.instance
    authorize! :update, @scheme
  end

  def update
    @scheme = Iqvoc::Concept.root_class.instance
    authorize! :update, @scheme

    if @scheme.update_attributes(concept_params)
      flash[:success] = t('txt.controllers.concept_scheme.save.success')
      redirect_to scheme_path
    else
      flash[:error] = t('txt.controllers.concept_scheme.save.error')
      render :edit
    end
  end

  private
  def concept_params
    params.require(:concept).permit!
  end
end

app/helpers/concepts_helper.rb
# encoding: UTF-8

# Copyright 2011-2013 innoQ Deutschland GmbH
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

module ConceptsHelper
  # if `broader` is supplied, the tree's direction is reversed (descendants represent broader relations)
  def treeview(concepts, broader = false, dragabble = false)
    render "concepts/hierarchical/treeview", concepts: concepts, broader: broader, dragabble: dragabble
  end

  # turns a hash of concept/relations pairs of arbitrary nesting depth into the
  # corresponding HTML list
  def nested_list(hash, options={})
    ordered = options[:ordered] || false
    options.delete(:ordered)

    content_tag(ordered ? 'ol' : 'ul', options) do
      hash.map do |concept, rels|
        rels.empty? ? content_tag('li', concept) : content_tag('li') do
          h(concept) + nested_list(rels, ordered: ordered) # NB: recursive
        end
      end.join("\n").html_safe
    end
  end

  def letter_selector(letters = ('A'..'Z').to_a, &block)
    highlighted_letter = params[:prefix] || letters.first || 'a'
    content_tag :ul, class: 'letter-selector list-unstyled' do
      letters.map do |letter|
        content_tag :li, link_to(letter, yield(letter)),
          class: ('active' if highlighted_letter.to_s.downcase == letter.to_s.downcase)
      end.join('').html_safe
    end
  end

  # Renders associated objects of a given concept to a hash structure.
  # This hash is taken by view/layouts/_sections to be rendered.
  def concept_view_data(concept)
    res = {}

    render_concept_association(res, concept, Collection::Member::Base)

    Iqvoc::Concept.labeling_classes.each do |labeling_class, languages|
      render_concept_association(res, concept, labeling_class, available_languages: languages || Iqvoc.available_languages)
    end

    Iqvoc::Concept.relation_classes.each do |relation_class|
      render_concept_association(res, concept, relation_class)
    end

    render_match_association(res, concept, Iqvoc::Concept.match_classes)

    Iqvoc::Concept.note_classes.each do |note_class|
      render_concept_association(res, concept, note_class)
    end

    Iqvoc::Concept.notation_classes.each do |notation_class|
      render_concept_association(res, concept, notation_class)
    end

    Iqvoc::Concept.additional_association_classes.keys.each do |assoc_class|
      render_concept_association(res, concept, assoc_class)
    end

    res
  end

  def delete_button_text(concept)
    concept.never_published? ? t("txt.views.versioning.delete") : t("txt.views.versioning.delete_copy")
  end

  def concept_header(concept)
    desc = concept.class.model_name.human

    if concept.expired_at
      desc += " #{t('txt.views.concepts.expired_at', date: l(concept.expired_at, format: :long))} "
    end

    title = concept.pref_label || concept.origin

    page_header title: title.to_s, desc: desc.html_safe
  end

  private

  # Renders a partial taken from the .partial_name method of the objects
  # associated to the concept.
  def render_concept_association(hash, concept, association_class, further_options = {})
    html = if association_class.respond_to?(:hidden?) && association_class.hidden?(concept)
      ''
    else
      render(association_class.partial_name(concept), further_options.merge(concept: concept, klass: association_class))
    end
    # Convert the already safely buffered string back to a regular one
    # in order to be able to modify it with squish
    if String.new(html).squish.present?
      ((hash[association_class.view_section(concept)] ||= {})[association_class.view_section_sort_key(concept)] ||= '') << html.html_safe
    end
  end

  def render_match_association(hash, concept, association_classes, further_options = {})
    matches_html = ''
    association_classes.each do |association_class|
      matches_html += if association_class.respond_to?(:hidden?) && association_class.hidden?(concept)
        ''
      else
        render(association_class.partial_name(concept), further_options.merge(concept: concept, klass: association_class))
      end
    end
    html = render partial: '/partials/match/panel', locals: { body: matches_html }
    if String.new(html).squish.present?
      ((hash[association_classes.first.view_section(concept)] ||= {})[association_classes.first.view_section_sort_key(concept)] ||= '') << html.html_safe
    end
  end
end

app/views/concepts/_form.html.erb
<%= bootstrap_form_for concept,
    :as => :concept,
    :url => concept.new_record? ? concepts_path : concept_path(:published => 0, :id => concept),
    :layout => :horizontal do |f| %>

  <!-- Base data -->
  <fieldset>
    <legend><%= t('txt.common.attributes') %></legend>
    <%= f.text_field :follow_up, :class => 'datepicker' %>
    <%= f.text_field :expired_at, :class => 'datepicker' %>

    <%- Iqvoc::Concept.additional_association_classes.keys.each do |assoc_class| -%>
      <%= render assoc_class.edit_partial_name(concept),
        :concept => concept, :klass => assoc_class, :f => f %>
    <%- end -%>
  </fieldset>
  <!-- / Base data -->

  <!-- Labelings -->
  <fieldset>
    <legend><%= Labeling::Base.model_name.human(:count => 2) %></legend>
    <% unless Iqvoc.const_defined?(:SKOSXL) %>
      <p><%= t 'txt.common.hint_csv_input' %></p>
    <% end %>
    <%- Iqvoc::Concept.labeling_classes.each do |labeling_class, languages| -%>
      <%- languages.each do |language| -%>
        <%= render labeling_class.edit_partial_name(concept), :f => f,
          :concept => concept, :klass => labeling_class, :language => language %>
      <%- end -%>
    <%- end -%>
  </fieldset>
  <!-- / Labelings -->

  <!-- Concept relations -->
  <fieldset>
    <legend><%= Concept::Relation::Base.model_name.human(:count => 2) %></legend>
    <% unless Iqvoc::Concept.broader_relation_class.edit_partial_name(concept).nil? %>
      <%- if Iqvoc::Concept.broader_relation_class.narrower_editable -%>
        <%= render Iqvoc::Concept.broader_relation_class.narrower_class.edit_partial_name(concept),
          :concept => concept, :klass => Iqvoc::Concept.broader_relation_class.narrower_class, :f => f %>
      <%- end -%>

      <%= f.form_group :top_term do %>
        <%= f.check_box :top_term,
          :class => ("exclusive" if Iqvoc::Concept.broader_relation_class.singular?) %>
      <% end %>

      <%= render Iqvoc::Concept.broader_relation_class.edit_partial_name(concept),
        :concept => concept, :klass => Iqvoc::Concept.broader_relation_class, :f => f %>
    <% end %>

    <%- Iqvoc::Concept.further_relation_classes.each do |relation_class| -%>
      <%= render relation_class.edit_partial_name(concept),
        :concept => concept, :klass => relation_class, :f => f %>
    <%- end -%>
  </fieldset>
  <!-- / Concept relations -->

  <!-- Collections -->
  <fieldset>
    <legend><%= Iqvoc::Collection.base_class.model_name.human(:count => 2) %></legend>
    <%= f.form_group :assigned_collection_origins, :label => {:text => t('txt.common.type_to_search')} do %>
      <%= text_field_tag "concept[assigned_collection_origins]",
        concept.assigned_collection_origins.join(InlineDataHelper::JOINER),
        :class => "entity_select",
        :"data-query-url" => collections_path(:format => :json),
        :"data-entity-uri" => collection_path(:id => "{id}"),
        :"data-entities" => concept.collections.map { |c| collection_widget_data(c) }.to_json %>
    <% end %>
  </fieldset>
  <!-- /Collection -->

  <!-- Notes ohne Change Note class -->
  <% Iqvoc::Concept.note_classes.reject { |n| n == Iqvoc.change_note_class  }.each do |note_class| %>
    <% unless note_class.edit_partial_name(concept).nil? %>
      <%= render note_class.edit_partial_name(concept), :owner_klass => concept, :assoc_klass => note_class, :f => f %>
    <% end %>
  <% end %>
  <!-- / Notes -->

  <!-- Matches -->
  <fieldset class="matches" data-datasets="<%= @datasets %>" data-remote-proxy-url="<%= alphabetical_concepts_path %>" data-translation-other="<%= t('txt.common.other') %>" data-no-results-msg="<%= t('txt.views.search_results.no_results') %>">
    <legend><%= Match::Base.model_name.human(:count => 2) %></legend>
    <% Iqvoc::Concept.match_classes.each do |match_class| %>
      <%= render match_class.edit_partial_name(concept), :owner_klass => concept, :assoc_klass => match_class, :f => f %>
    <% end %>
  </fieldset>
  <!-- / Matches -->

  <!-- Notations -->
  <% Iqvoc::Concept.notation_classes.each do |notation_class| %>
    <%= render notation_class.edit_partial_name(concept), :owner_klass => concept, :assoc_klass => notation_class, :f => f %>
  <% end %>
  <!-- / Notations -->

  <!-- Change Note class -->
  <% note_class = Iqvoc.change_note_class %>
  <% unless note_class.edit_partial_name(concept).nil? %>
    <%= render note_class.edit_partial_name(concept), :owner_klass => concept, :assoc_klass => note_class, :f => f %>
  <% end %>
  <!-- / Change Note class -->

  <hr />

  <div class="well">
    <%= f.submit t("txt.common.save"), :class => "btn btn-primary" %>

    <%= link_to t("txt.common.cancel"), concept.new_record? ? dashboard_path : concept_path(:published => 0, :id => concept), :class => "btn btn-default" %>
  </div>

<% end %>

app/views/concepts/_header.html.erb
<% published_param = concept.published? ? nil : 0 %>
<%= content_for :head do -%>
  <link href="<%= rdf_url(concept.origin, :format => :ttl, :published => published_param, :lang => nil) %>" type="text/turtle" rel="alternate" title=""/>
  <link href="<%= rdf_url(concept.origin, :format => :rdf, :published => published_param, :lang => nil) %>" type="application/rdf+xml" rel="alternate" title=""/>
  <link href="<%= concept_path(concept, :format => :json, :published => published_param) %>" type="application/json" rel="alternate"/>
<% end -%>

<%= concept_header concept %>

app/views/concepts/edit.html.erb
<%= render 'header', :concept => @concept %>
<%= render 'concepts/sidebars/singular', :concept => @concept %>

<%= error_messages_for @concept %>

<%= render 'concepts/notifications/referenced_concepts',
  :association_objects_in_editing_mode => @association_objects_in_editing_mode %>

<%= render 'form', :concept => @concept %>

app/views/concepts/glance.html.erb
<!-- Modal -->
<div class="modal-dialog concept-teaser-dialog">
  <div class="modal-content concept-teaser-content">
    <div class="modal-header concept-teaser-header">
      <button type="button" class="close" data-dismiss="modal">
        <span aria-hidden="true">&times;</span>
        <span class="sr-only"><%= t('txt.views.concepts.teaser.close') %></span>
      </button>
      <h1 class="modal-title" id="concept-teaser-title"><%= @concept.pref_label %></h1>
    </div>
    <div class="modal-body concept-teaser-body">
      <% if @view.no_content? %>
      <div class="alert alert-warning" role="alert">
        <%= t('txt.views.concepts.teaser.no_content') %>
      </div>
      <% end %>
      <% if @view.definition %>
      <div>
        <h2><%= Note::SKOS::Definition.model_name.human %></h2>
        <p><%= @view.definition %></p>
      </div>
      <% end %>
      <% if @view.alt_labels.any? %>
      <div>
        <h2><%= Iqvoc::Concept.alt_labeling_class.model_name.human(count: 2) %></h2>
        <ul class="label-list">
          <% @view.alt_labels.each do |l| %><!--
          --><li class="label-list-item">
               <span class="label-list-item-value"><%= l.value %></span>
             </li><!--
          --><% end %>
        </ul>
      </div>
      <% end %>
      <% if @view.collections.any? %>
      <div>
        <h2><%= Iqvoc::Collection.base_class.model_name.human(count: 2) %></h2>
        <ul>
          <% @view.collections.each do |c| %>
            <li><%= link_to c.caption, c.uri %></li>
          <% end %>
        </ul>
      </div>
      <% end %>
      <% if @view.related.any? %>
      <div>
        <h2><%= Iqvoc::Concept.further_relation_classes.first.try { |klass| klass.model_name.human(count: 2) } %></h2>
        <ul>
          <% @view.related.each do |c| %>
            <li><%= link_to c.caption, c.uri %></li>
          <% end %>
        </ul>
      </div>
      <% end %>
    </div>
    <div class="modal-footer concept-teaser-footer">
      <a href="<%= concept_path(@concept) %>" class="btn btn-default"><i class="fa fa-angle-double-right"></i> <%= t('txt.views.concepts.to_concept') %></a>
    </div>
  </div>
</div>
<!-- / Modal -->

app/views/concepts/new.html.erb
<%= page_header :title => t("txt.views.concepts.new", :concept_class_name => Iqvoc::Concept.base_class.model_name.human(:count => 1)) %>

<%= error_messages_for @concept %>
<%= render 'concepts/form', :concept => @concept %>

app/views/concepts/show_published.html.erb
<%= render 'header', :concept => @concept %>
<%= render 'concepts/sidebars/singular', :concept => @concept %>

<% if @new_concept_version.blank? && can?(:branch, @concept) %>
  <% if @jobs && @jobs.any? %>
    <%= render partial: 'partials/concept/reverse_match_notice', locals: {concept: @concept, jobs: @jobs} %>
  <% end %>
    <div class="editing_versioning_toolbar well">
      <%= button_to t("txt.views.versioning.versioning_mode"),
        concept_versions_branch_path(:origin => @concept.origin), :class => "btn btn-default" %>
    </div>
<% elsif can?(:read, @new_concept_version) %>
    <div class="editing_versioning_toolbar well">
      <%= link_to t("txt.views.versioning.preview_new_version"),
        concept_path(:published => 0, :id => @new_concept_version), :class => 'btn btn-default' %>
    </div>
<% end %>

<%= render 'layouts/sections', :sections => Iqvoc::Concept.view_sections, :data => concept_view_data(@concept) %>